# charts/backend-fastapi/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbot-backend.fullname" . }}
  labels: 
    {{ include "chatbot-backend.labels" . | nindent 4 }}
data:
  {{ range $key, $val := .Values.env}}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  