apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbot-backend.fullname" . }} # flow file _helpers.pkl
  labels: 
    {{ include "chatbot-backend.labels" . | nindent 4 }} # flow file _helpers.pkl

spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      {{ include "chatbot-backend.selectorLabels" . | nindent 6 }}
  
  template:
    metadata:
      labels: {{ include "chatbot-backend.selectorLabels" . | nindent 8}}

      annotations:
        # Dòng này sẽ thay đổi khi giá trị trong config thay đổi, buộc K8s phải restart Pod
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: 
            - name: http 
              containerPort: 8000
          
          envFrom: 
            - configMapRef:
                name: {{ include "chatbot-backend.fullname" . }}
            - secretRef: 
                name: {{ include "chatbot-backend.fullname" . }}
          
          resources: {{ toYaml .Values.resources | nindent 12}}

          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}