apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbot-frontend.fullname" . }}
  labels: 
    {{ include "chatbot-frontend.labels" . | nindent 4 }}
data:
  {{ range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  