apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "chatbot-frontend.fullname" . }} # flow file _helpers.tpl
  labels: 
    {{ include "chatbot-frontend.labels" . | nindent 4 }} # flow file _helpers.tpl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "chatbot-frontend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels: {{ include "chatbot-frontend.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8501 
          envFrom:
            - configMapRef:
                name: {{ include "chatbot-frontend.fullname" .}}
            # - secretRef: 
            #     name: {{ .Values.secretName }}
          resources: {{ toYaml .Values.resources | nindent 12}}