apiVersion: v1 
kind: Secret
metadata:
  name: {{ include "chatbot-frontend.fullname" . }}
  labels: {{ include "chatbot-frontend.labels" . | nindent 4}}

type: Opaque # secret generic (không phải TLS hay Docker registry)
data:
  {{ range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | b64enc | quote }} # mã hóa base64 (bắt buộc với Secret)
  {{ end }}
  